name: GitHub Pagesへ公開

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: true

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: ソースを取得
        uses: actions/checkout@v4
      - name: Node.jsを準備
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: npm
      - name: 必要な部品を準備
        run: npm ci
      - name: テスト
        run: npm test
      - name: 静的ファイル作成
        run: npm run build:pages
      - name: GitHub Pagesを準備
        uses: actions/configure-pages@v5
      - name: 公開ファイルを登録
        uses: actions/upload-pages-artifact@v3
        with:
          path: out
      - name: 公開
        id: deployment
        uses: actions/deploy-pages@v4
